[package]
name = "codegen-experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"

[build-dependencies]
anyhow = "1.0.103"
prettyplease = "0.2.37"
proc-macro2 = "1.0.106"
quote = "1.0.46"
serde = { version = "1.0.228", features = ["derive"] }
syn = "2.0.118"
toml = "1.1.2"
